### ISSUE TITLE
Dependencies for `decker crunch` broken

### ISSUE THREAD

**Issue by mbotsch** [decker-edu/decker#100]
Recording a video and converting the WEBM to MP4 by `decker crunch`, then re-recording and replacing the WEBM (because you messed up something) and calling `decker crunch` does ignore the new WEBM.

![Screenshot 2024-01-14 at 18 20 21](https://github.com/decker-edu/decker/assets/31275467/f007312c-4984-404e-8ba5-6af30e79845f)

Deleting the old MP4 currently is the only way to resolve the problem.

**Comment by monofon** [comment]
Sadly, this can be confirmed.

**Comment by monofon** [comment]
@mbotsch Well, does it?
