### ISSUE TITLE
Massive storage usage of Decker after short period of time

### ISSUE THREAD

**Issue by Robby3St** [decker-edu/decker#102]
The decker browser tab uses massive amount of RAM after running decker for an hour while slide development. 

<img width="1072" alt="Bildschirmfoto 2024-01-29 um 15 39 47" src="https://github.com/decker-edu/decker/assets/35135025/582ad63f-56b0-4510-80cb-a241d17a8162">

**Comment by monofon** [comment]
Interesting.

I always assumed that reloading a page would free all resources of the previous instantiation.

I am currently running `decker -S` on `test/decks/media-deck.md` with a touch (and subsequent reload) in a 5 second loop and see an increase in memory from 500 MB to in 2,5 GB in just 2 Minutes on Safari.

**Comment by monofon** [comment]
Memory usage easily goes up to 10 GB which starts to increase memory pressure on the system.

A manual page reloads resets the memory usage of the tab immediately.

**Comment by monofon** [comment]
Only on Safari ...

Chrome behaves just fine.

**Comment by salbeira** [comment]
In addition:

`.decker/.shake.database` is getting quite large and larger on every reload (200 MB in some cases)

**Comment by monofon** [comment]
This is bad, but certainly not related, please open a new issue.

Also, i do not understand what you are saying here:

> it seems like shake is corrupting its own database by writing bytes in ascending values to the .database

**Comment by monofon** [comment]
Closed in favour of #104.
