### ISSUE TITLE
Reveal plugin integration

### ISSUE THREAD

**Issue by Hexanders** [decker-edu/decker#119]
Is it possible to integrate revel.js plugins without changing too much code? I could not find any information in the Decker documentation. 

I am mainly interested in the simplemenu plugin.

https://github.com/Martinomagnifico/reveal.js-simplemenu

It would be very nice to integrate this.

**Comment by salbeira** [comment]
Reveal Plugins are loaded inside a resource pack's template. I tore the system a bit apart in recent commits so you only need to copy and modify the `deck-plugins.html` partial to modify the loaded plugins (and the `deck-styles.html` if the plugin brings .css files with it).

You either need to fork and modify the related template that you are using or create a custom resource pack that you load and integrate locally. The vs-code plugin "decker-init" can help you create a directory in your project that has a structure to be accepted as a resource pack, though without any modified contents. Also remember that resource-packs always modify the default "exe:decker" resource pack and have no inheritance hierarchy.
