### ISSUE TITLE
color-mode overwrite required

### ISSUE THREAD

**Issue by marcerich** [decker-edu/decker#127]
We currently do not have a way to overwrite the color-mode attribute for a slide set nor can we disable the color mode switch in the UI. However, there are  several use-cases where this is required. First, not always do we have time to optimise all images etc  to support both modes. Second, one might want to make slides available to the public (e.g., after a talk) but cannot assume the audience to be aware of the decker options in the menu, hence the might see the slides in the unsupported and then awkward dark mode not knowing how to change this. Hence it would be really great if we could superset the color-mode attribute at least on first load per slide set.

**Comment by mbotsch** [comment]
You can now add 
``` yaml
colorscheme: "light"
```
to you YAML settings.

**Comment by marcerich** [comment]
Thanks for the swift update. It works out of the box when you serve the slides locally. However, if the slides get published to a remote server, these settings are lost. Hence for the main reason to publish materials on a server for some guests it  doesn't quite do the trick at the moment...

**Comment by mbotsch** [comment]
It works for me: https://cg.cs.tu-dortmund.de/downloads/elearning/slides/eLearning-deck.html
Maybe your old version is still cached?

**Comment by marcerich** [comment]
works
