### ISSUE TITLE
Decker 0.13.0 Windows and Manjaro presentation build error

### ISSUE THREAD

**Issue by MatthiasPopp** [decker-edu/decker#25]
I tried to compiled the repo at commit 90893d1 as well as RC2 with a fresh Windows 10 and up-to-date Manjaro OS. By using the regular `decker html` I do have issues to compile an existing presentation. On MacOs it compiles fine. The same goes for Decker 0.12 for all platforms.

The presentation is one of @marcerich lectures and the error is as follows
```# pandoc (for public/exercises/14-exam-preparation-page.html)
Error when running Shake build system:
  at want, called at src/Text/Decker/Project/Shake.hs:70:16 in decker-0.13.0-F2g1oeUEJMuKwu8gOb4JYR:Text.Decker.Project.Shake
* Depends on: html
  at need, called at app/Decker.hs:52:3 in main:Decker
* Depends on: public/exercises/09-latency-quiz-deck.html
  at error, called at src/Text/Decker/Resource/Template.hs:68:35 in decker-0.13.0-F2g1oeUEJMuKwu8gOb4JYR:Text.Decker.Resource.Template
  at error, called at src/Relude/Debug.hs:289:11 in relude-1.1.0.0-7JT7B2uwFcC7TQpV8XiQyh:Relude.Debug
* Raised the exception:
# compilation of pack template failed: template/deck.html,  error: (line 206, column 39):
unexpected "\""
expecting "$", "{", "if", "for", "~", "^", letter, "it" or letter or digit
```

The source file syntax is correct and does have the character `\`. It is part of a latex command 

Here is the problematic section:

```
## 

<span style="font-size: x-small;"> Bos, Jelte E, Sjoerd C de Vries, Martijn L van Emmerik, and Eric L Groen. 2010. “The Effect of Internal and External Fields of View on Visually Induced Motion Sickness.” Applied Ergonomics 41 (4). Elsevier: 516–21</span>

<span style="font-size: x-small;"> Kennedy, Robert S., Norman E. Lane, Kevin S. Berbaum, and Michael G. Lilienthal. 1993. “Simulator Sickness Questionnaire: An Enhanced Method for Quantifying Simulator Sickness.” The International Journal of Aviation Psychology 3 (3): 203–20. doi:10.1207/s15327108ijap0303\textunderscore 3.</span>

<span style="font-size: x-small;"> Keshavarz, Behrang, and Heiko Hecht. 2011a. “Axis Rotation and Visually Induced Motion Sickness: The Role of Combined Roll, Pitch, and Yaw Motion.” Aviation, Space, and Environmental Medicine 82 (11). Aerospace Medical Association: 1023–29.</span>

<span style="font-size: x-small;"> Keshavarz, Behrang, and Heiko Hecht. 2011b. “Validating an Efficient Method to Quantify Motion Sickness.” Human Factors 53 (4). Sage Publications Sage CA: Los Angeles, CA: 415–26. </span>
```
The decker example slide compiles just fine though.

If you need further info on the file contents, please PM me.

Any suggestions how I can fix/debug that?

**Comment by monofon** [comment]
Assuming you use the `nwburg` resource pack, it looks like something in a comment in the slide template confuses the Pandoc template compiler. I removed the entire comment. Please try *v0.13.0-RC3* once it is ready.

**Comment by MatthiasPopp** [comment]
Hey @monofon ,
yes I am using the `nwburg` resource pack. RC3 still has the issue. Switching to `resource-pack: exe:mono` or `resource-pack: exe:decker` compiles successfully. 
A quick attempt suggests that the definition for `asm6502acme` incorrectly causes HighlightJS to parse the file.

**Comment by MatthiasPopp** [comment]
Escaping the `$` signs in the definition seems to help. I.e. 
`r.COMMENT(";", "$", { relevance: 0 }),` -> `r.COMMENT(";", "$$", { relevance: 0 }),` 
Strange but I will test the result tomorrow.

**Comment by MatthiasPopp** [comment]
#26 solved my issue. Thanks for merging!
