### ISSUE TITLE
Report errors on stderr?

### ISSUE THREAD

**Issue by salbeira** [decker-edu/decker#30]
I just mentioned that decker reports errors simply as colored text on stdout instead of writing errors to stderr (which usually is then colored by the terminal). Is there a reason for it and does anything speak against actually using the stderr for error reporting?

**Comment by monofon** [comment]
The reason is that the shake library reports exceptions that way.

Would there be any advantage to actually using stderr for error reporting?

**Comment by salbeira** [comment]
For our vs code plugins it would be neat to actually know what messages sent are errors and what are just status messages because if a server is running and you include e.g. a non existing image, compilation fails but you are not informed about it because the server just keeps running but no changes happen. If the error would be reported over stderr I would be able to actually report the fact to the user.

**Comment by monofon** [comment]
Try `decker --help`. 😁

**Comment by salbeira** [comment]
Option `-e` seems to work. Thanks.
