### ISSUE TITLE
Mark Link as download

### ISSUE THREAD

**Issue by salbeira** [decker-edu/decker#32]
We had a case where we wanted a user to download an example image but linking it in a deck with `[Download](URL)` causes the browser to open the file as an image. You can mark anchors as explicit download links in HTML:

``` html
<a href="" download>Download</a>
```

It would be neat if we could mark links as such in markdown as well:

```
[Download](URL){download}
```

**Comment by monofon** [comment]
Try 

```markdown
[Download](assets/picard-facepalm.jpeg){download=""}
```

**Comment by salbeira** [comment]
That does indeed work but for mere usability I feel allowing simply "download" just like in the html tag would be more concise but I will write that down for now.

**Comment by monofon** [comment]
Just `download` is difficult to implement, because Pandoc does not support it. We would need a custom Pandoc parser.

**Comment by monofon** [comment]
How about

```markdown
[Download](assets/picard-facepalm.jpeg){download="fuck, yes"}
```

`.download` would be a class not an attribute. If you can come up with some CSS that makes this trigger a download, go for it.

**Comment by salbeira** [comment]
OK, I thought that because we have classes like `.embed` or `.details` that parsing the link for the class would be easier.

**Comment by monofon** [comment]
Both `.embed` and `.details` are not classes that are just translated into attributes.
