### ISSUE TITLE
Default Option of Select-Box quizzes is always "..."

### ISSUE THREAD

**Issue by salbeira** [decker-edu/decker#33]
Our accessibility team recommended that we do not use "..." as the default value for selection box quizzes but something that is an understandable call to action.

It seems that this is not managed by the quiz-wue.js plugin but created by this:

https://github.com/decker-edu/decker/blob/c4238f4fdb1b6ac7ace5954d040fbb05bd043407/src/Text/Decker/Filter/Quiz.hs#L295

Can we make the text of default answers or placeholders in all quiz types configurable?

**Comment by monofon** [comment]
What would an "understandable call to action" be in this case?

Making syntax configurable is something I would rather not do. We could talk about a syntactic alternative, though. So the question is, what would be an alternative syntax that is arguably better (for some version of better).

**Comment by mbotsch** [comment]
I think I added this in f4c51967bc3f6e402bb6225b7e14e4348e712f22

**Comment by monofon** [comment]
Ok, so it is not syntax, just localized text. I did not get that from the description.
