### ISSUE TITLE
Where would a table-of-contents come from?

### ISSUE THREAD

**Issue by salbeira** [decker-edu/decker#36]
While looking at our template files I mentioned that every single one of them has a 

`$if(toc)$ [insert $table-of-contents$ into html] $endif$`.

Yet I can not find any mention of a "toc" or "table-of-contents" variable inside the haskell sources or in any test or example.

@mbotsch also told me that he never used the feature at all (yet we still include it diligently in our tudo templates).

@monofon is there any way to make use of this or can it be removed from the template files?

Similarily the `$idprefix$` variable used before toc and title-slide ids does not seem to be in use at all.

**Comment by monofon** [comment]
These variables are part of the default Pandoc templates. We can remove them, I think.
