### ISSUE TITLE
Minimize rsync's default arguments

### ISSUE THREAD

**Issue by salbeira** [decker-edu/decker#40]
We currently have two ways to configure `decker publish`.

One old way where parameters for `rsync` were not configurable and a new way where this is possible.

Right now several arguments for `rsync` are hard coded inside the `decker publish` call.

This creates extra headaches if you want to adapt the `decker publish` command for new environments.

In our discussion we came to the conclusion that the truly required arguments are `--recursive`, `--copy-links` and `--delete`.

Should the "old" way of using `decker publish` even be documented? Is it anywhere? The user-guide currently documents the *new* way if I interpret it correctly.

**Comment by salbeira** [comment]
The default arguments right now are:

`--recursive --no-group --perms --chmod=a+r, go-w --no-owner --copy-links` found in External.hs

**Comment by monofon** [comment]
@marcerich , @mbotsch please update your local `decker.yaml` files in case you set your own rsync options.
