### ISSUE TITLE
Can we reenable MathJax's accessibility features?

### ISSUE THREAD

**Issue by salbeira** [decker-edu/decker#46]
In the code of our math plugin that initializes MathJax it is written that the mml features of MathJax break the speaker notes plugin.

That plugin itself is broken because of a cyclic reference that gets stringified somewhere, but that is beside this issue.

I tried reenabling all the a11y/xyz features of MathJax and do not encounter any new errors or changes to behaviour in the `math-deck.md` Test that especially uses math in hidden speaker notes.

Can we reenable these plugins in general or does it break on anyone's end? Please check the `reenable-mathjax-a11y` branch and give some feedback on if the enabled features are annoying or distracting - then we can discuss how we want to configure the features if necessary.

@mbotsch How did it break back in the day in the first place?

**Comment by salbeira** [comment]
So Mario explained to me what broke: Inside the speaker notes the math formulas seem to be duplicated.

This is indeed still the case but the duplication is simply the MML Code next to the SVG-Element being rendered. As they are rendered in different fonts they looked like two different formulas to me at first.

As MathJax inserts the style tag containing the CSS rules that usually hide the MML code via their javascript plugins and the speaker notes have a hard-coded html structure that is compiled into the notes.esm.js that we use as the plugin source it is not trivial to get the relevant css into the speaker notes webpage.

I extracted the notes plugin from the reveal vendor directory and modified it so it loads a modified speaker view webpage that contains the mathjax mml css. This seems to fix this issue.

**Comment by mbotsch** [comment]
We should not have our own version of the notes plugin, to keep maintainance effort reasonable.
A11y should be more important than non-messed-up speaker notes, so maybe we re-enable it.

However, we have to make sure that users cannot break MathJax by selecting something weird in the MathJax menu. Can we  have a11y without the MathJax menu? Can we remove all non-a11y items from the menu?

**Comment by salbeira** [comment]
Feature was merged.
