### ISSUE TITLE
Mac install package seems broken

### ISSUE THREAD

**Issue by cschell** [decker-edu/decker#48]
Hi,

when I click on "[decker-v0.13.2-macOS-X64](https://github.com/decker-edu/decker/releases/download/v0.13.2/decker-v0.13.2-macOS-X64)" in the release section, it downloads the file without the ".pkg" ending. If I add the ending, it fails, saying it cannot be opened:
![Bildschirmfoto 2023-07-19 um 11 56 13](https://github.com/decker-edu/decker/assets/493711/cdf47761-2a55-47ac-8f26-f02f1525db10)

**Comment by cschell** [comment]
I just realized that this is the actual binary, not an installer. Sorry for the noise, perhaps this could be added to the Readme :)

**Comment by monofon** [comment]
Yes, it is. Your are right, this is not at all documented.
