### ISSUE TITLE
Recording Tab Selection is now handled differently by browsers

### ISSUE THREAD

**Issue by salbeira** [decker-edu/decker#58]
In the most recent chrome version on Windows I can only choose the current tab as a video stream source. There is no option to pick a different tab, window or screen.

In the most recent chrome version on Linux I can NOT choose the current tab as a video stream source. Everything BUT the current tab is an option.

Using the current develop branch.

EDIT: This even happens with the old 0.12 version.

Can anyone confirm this?

**Comment by salbeira** [comment]
Seems like the newest browser versions are now enforcing some changes propsed last year:

The browser will, by default, hide the current tab from selection so that WebRTC applications do not have a "hall of mirrors" effect when opening the selecion interface. You need to specify "selfBrowserSurface: 'include'" in the getDisplayMedia()-options to have the current tab available for sharing.

In addition, "preferCurrentTab", under Windows, displays an entriely different interface that ONLY presents the current tab:

![grafik](https://github.com/decker-edu/decker/assets/3225441/239b32fc-c80c-45b4-a039-b964ea9f73df)

**Comment by salbeira** [comment]
Some more screenshots:

Without "preferCurrentTab" and without "selfBrowserSurface":

![grafik](https://github.com/decker-edu/decker/assets/3225441/f2080bdc-57c3-46f7-8bb9-1f167e3da237)

With selfBrowserSurface:

![grafik](https://github.com/decker-edu/decker/assets/3225441/b3262746-38c4-4994-aa4d-4c9d1236c565)

**Comment by mbotsch** [comment]
Should be fixed in master branch and develop branch. Could you please test it on Linux and Windows?

**Comment by monofon** [comment]
Someone please test this with the released v0.13.4 on Windows.

**Comment by salbeira** [comment]
Tested on both Windows and Linux on both master and develop built from source.
Also tested it with the executable inside the releases.
I can select the decker-tab as a source (and have the usual selection of window and screen again)
Closing the issue.
