### ISSUE TITLE
Background videos don't play on Safari

### ISSUE THREAD

**Issue by monofon** [decker-edu/decker#6]
At all. Look at `test/decks/background-video-deck.md`.

HTML looks right, though. Something with Reveal.js?

**Comment by salbeira** [comment]
Works for me on both Chrome and Firefox. First two examples show a video of a rotating scene once. The final one repeats indefinetly.

**Comment by monofon** [comment]
Yes, seems to be a Safari problem (@mbotsch any comments 😄).

Even this does not work:

```html
<html>
  <head>
    <script type="module">
      import Reveal from "./../../support/vendor/reveal/dist/reveal.esm.js";
      let deck = new Reveal({});
      deck.initialize();
    </script>
  </head>

  <body>
    <div class="reveal">
      <div class="slides">
        <section
          class="slide level1"
          data-background-video="movie.mp4"
        ></section>
      </div>
    </div>
  </body>
</html>
```

**Comment by mbotsch** [comment]
As much as I dislike Safari: It works on my system.

Branch develop
MacOS 12.6
Safari 16.0

**Comment by monofon** [comment]
It absolutely refuses to work here. Latest Safari, all plugins disabled, after restart of the system:

https://user-images.githubusercontent.com/825193/192129939-e9e18c99-e923-4cf8-9644-e268064345c7.mov

**Comment by monofon** [comment]
Seems to be my Safari installation. Works with *Safari Technology Preview*. Strange.
