### ISSUE TITLE
Menu and Feedback Plugin get initialised in print mode

### ISSUE THREAD

**Issue by salbeira** [decker-edu/decker#60]
The menu and feedback plugin should just not be initialised if we print a pdf so the menu containers are never even added to the DOM. This should make it impossible for the elements to creep into the printed page in any way.

**Comment by mbotsch** [comment]
The bug Daniele reported was already fixed in commit 8cf3ec2bf82d6c8049f8bc2cdddaeee1d55858f0

**Comment by salbeira** [comment]
Hmh yes but wouldn't this also future proof the issue against other changes to css rules?
