### ISSUE TITLE
Have more information - especially about remote connection wellbeing - in quiz plugin

### ISSUE THREAD

**Issue by salbeira** [decker-edu/decker#62]
It turns out the one thing we absolutely can not rely on is a stable internet connection in our lecture halls, especially if we have over 400 participants that all bring 1 - 3 devices of which at least one is used to open a wifi hotspot (resulting in more SSIDs being visible than any WiFi User Interface can manage).

Right now if the connection to the quiz server breaks, clicking on the "view QR code" or "start poll" button either does nothing or opens a broken link (that directs the scanning participant to a quiz session that simply says "Error").

Right now it seems there is no way to:

a) Regenerate the QR code (start a new poll session) without reloading the page.
b) Reconnect to an existing session as a host after changing connection types (e.g. going from one wifi network to another or switching to a cabled connection or connecting to a vpn after already having opened the slides)
c) Inform the clients about their connection's wellbeing and if their host is still connected at all (and what kind of "Error" occurred if we get an error - simply "connection lost" or "host lost connection" would suffice to make it clear that it is an error the user can not influence - clarifying that an error is due to circumstance and not the fault of the tool or the user)
d) See if the connection to the poll server is possible at all (e.g. in Fullscreen you do not see your WiFi icon in the Taskbar, and even then you might have a connection to a WiFi Router but the Router may be in a panic and not allow an outgoing connection due to having too many people in your lecture hall ... or the universities DNS may be down again ... etc.) - The host is just confused that clicking on the button does nothing - no error or feedback to the user at all.

In addition we got several feature requests for the poll UI:

1) An informative text that informs the host he can close the QR-Code window by clicking anywhere
2) The poll's URL (the URL the clickable poll ID at the bottom links to) visible next to the QR-Code so users without a QR-Code scanner (e.g. students sitting there with their laptop) can participate by simply copying the link by hand)
3) The question being asked still being visible while the QR-Code is open so you do not have to close the QR-Code popup to make sure you read out the correct question.
4) A way to start the poll while the QR-Code is still visible.
5) For some reason the "complete" result of a poll can grow into the negatives.

@mbotsch can you clarify what the lifecycle of the poll is and if my assumtions on the behaviour of the plugin are correct? I tried to work through the plugin code but it is also mixed with @monofon 's examiner plugin for the poll session so I am unsure if there are actually more safeguards in place on the server side.

**Comment by mbotsch** [comment]
Will be implemented in a re-do of the quizzes
