### ISSUE TITLE
Video Recordings not playing in Safari any longer

### ISSUE THREAD

**Issue by marcerich** [decker-edu/decker#64]
On the development build of decker (version: 0.13.4, branch: develop) recordings of lectures made in the past with decker 0.12 do not play on Safari Version 16.6 on MacOS 13.5.2 (so up-to-date system based on M1) any longer. The page with the video playback is opened, it shows the controls and a black screen and an indefinetly spinning grey/white wheel as response.

However, when the same slideset and videos are opened on Chrome Version 118.0.5993.70 all is good and behaves as expected.

**Comment by mbotsch** [comment]
With Safari 17.0 on MacOS 14.0 both old and new recordings work as expected.

**Comment by marcerich** [comment]
Ack. Updated to Safari 17.0 on MacOS 14.0 both old  recordings work again as expected.
