### ISSUE TITLE
Ignore temporary files with --watch

### ISSUE THREAD

**Issue by kno10** [decker-edu/decker#65]
Watch mode is nice, but it causes a lot of spurious reloads for me because of VIM.

Please add the following:
- do not push a reload if no files were updated by decker
- ignore files by pattern, e.g., `.*`, `*.swp`, `*~` (e.g., VIM uses temporary files names `.filename.swp`, and stores a backup as `filename~`) - similar to `.gitignore`

**Comment by monofon** [comment]
I remember reconfiguring my vim to avoid this years ago. I never got around to fixing that in decker. 

There is however currently the meta data variable `exclude-directories` that allows exclusion of entire directories from watching. But that will not help you here.

I will look into it.

**Comment by kno10** [comment]
A workaround for VIM probably is `set directory=~/.cache/vim`, but I assume others will be affected, too.

**Comment by monofon** [comment]
@salbeira can you please test this on Windows. Add

```yaml
watch:
  exclude:
    - test/**/*.md
```

to `decker.yaml` and 

```sh
touch test/decks/media-deck.md
```

should not trigger a rebuild.

**Comment by monofon** [comment]
@mbotsch @salbeira please give it a quick check before I close this.

**Comment by salbeira** [comment]
Works for touch but opening the files with vim triggers the reload as advertised - I guess the idea is to include a glob that ignores vim swapfiles specifically for users who want that?

**Comment by monofon** [comment]
That is the idea.
