### ISSUE TITLE
Avoid password save prompts for question tokens

### ISSUE THREAD

**Issue by kno10** [decker-edu/decker#70]
I use incognito mode a lot, in particular for testing.

When switching slides I frequently get displayed the prompt to save/update the password in firefox, which is annoying.

Maybe the password field could be filled only on first use? Alternatively, if the field is named "token" and not "password" then it will likely not be saved, but I guess it is intentional to save it.

**Comment by monofon** [comment]
Assuming the admin password field on the feedback panel is the problem here, that behaviour is indeed intentional. 

Out of curiosity, why do you use incognito mode for testing?

**Comment by kno10** [comment]
Not the user+password login field in the bottom, but the pre-filled "user token" for the question functionality.
I open sites in incognito mode by default to frequently reset cookies. Also, this is very useful for simulating first visits and judging cross-browser behaviour.

**Comment by monofon** [comment]
I see. The token mechanism is actually overkill as it is. I'll look into removing that entirely.

**Comment by monofon** [comment]
@salbeira since you rewrote this whole thing, you get to remove the token field 😁 .
