### ISSUE TITLE
chrome command name is hardcoded

### ISSUE THREAD

**Issue by kno10** [decker-edu/decker#74]
The official Google chrome package on Debian (and likely also on Ubuntu) uses `/usr/bin/google-chrome-stable` (and the alternatives mechanism to manage `/usr/bin/google-chrome`).
Also, it would be nice to alternatively allow `chromium`.

I'd suggest to try to locate the following executables in order: `chrome`, `google-chrome`, `chromium` and maybe add an option to make this configurable by the user?

**Comment by salbeira** [comment]
This could and should be handled by #72
