### ISSUE TITLE
Add documentation for [:vspace](1em)

### ISSUE THREAD

**Issue by kno10** [decker-edu/decker#77]
This is a convenient macro to insert spacing, yet it is not mentioned in the documentation.

It would be good if the `clear:both` would be optional. I don't think a vspace implies a float barrier.

**Comment by monofon** [comment]
You might want to build your own vspace with a *template macro*:

```markdown
---
templates:
  vspace: |
    <div style="display:block; height::(url);"></div>
title: Custom vspace macro
---

Use it

[@vspace](10em)

like this.
```
