### ISSUE TITLE
Move color declatations from css-declarations to a css file/javascript?

### ISSUE THREAD

**Issue by kno10** [decker-edu/decker#82]
Almost 200 lines of redundant CSS are generated into the template from this fragment:
https://github.com/decker-edu/decker/blob/b0e9270953e826083388105827347bc9d843c319/resource/decker/template/deck.html#L37-L77
The computation of this CSS could be moved into JavaScript (but sequencing the loading of CSS may be a bit tricky, in case a user wants to override the values in a custom css file instead of using the configuration). Pandoc template syntax is not particularly powerful, or easy to modify, and the JSON file includes a copy of the entire CSS colors anyway.

**Comment by mbotsch** [comment]
Will be implemented in CSS, since color-mix is now widely available
