### ISSUE TITLE
Feature Request: Double click to enter a slide number

### ISSUE THREAD

**Issue by Robby3St** [decker-edu/decker#84]
The slide number is located in the right bottom corner. You got a left and a right arrow to move forwards and backwards. A feature would be nice to double click on the shown slide number to get a number input to immediately move to a specific slide (or single touch on mobile).

**Comment by mbotsch** [comment]
Thanks for suggesting this. However, to keep things simple and maintainable, we'll not add this feature. Users can simply open the menu and then select the desired slide.
