### ISSUE TITLE
Build of doc with bibliography fails

### ISSUE THREAD

**Issue by salbeira** [decker-edu/decker#9]
I get the following error:

```
CiteprocXMLError: Missing root element
Error when running Shake build system:
  at want, called at app/Decker.hs:75:3 in main:Decker
* Depends on: html
  at need, called at app/Decker.hs:47:25 in main:Decker
* Depends on: public/doc/smart-image-urls-page.html
* Raised the exception:
ExitFailure 4
```

OS: Linux Mint: 5.15.0-50-generic

decker check:
```
# external programs:
  ssh: found
  rsync: found
  dot: found
  plantuml: found
  gnuplot: found
  pdflatex: found
  pdf2svg: found
```

Commenting out the bibliography in the frontmatter of the doc-file resolves the issue.

**Comment by salbeira** [comment]
This seems to be related to:

https://github.com/decker-edu/decker/blob/e18681a8922a1e255e950742648312a41aa1f8c9/src/Text/Decker/Reader/Markdown.hs#L69

and

https://github.com/decker-edu/decker/blob/e18681a8922a1e255e950742648312a41aa1f8c9/src/Text/Decker/Reader/Markdown.hs#L82

But using -j1 does not work. Adding a csl meta value to the test and doc decks does fix the issue.

**Comment by monofon** [comment]
This already worked, and now should do race free.

**Comment by monofon** [comment]
@salbeira please give it a quick check before I close this.

**Comment by salbeira** [comment]
Omitting the `csl: [...]` meta variable in the `bibliography-deck.md`-Test does no longer fail. This seems to have fixed the issue.
